Repository NeotokyoRebuild/neo, pull requests merged in 2024-05, with the labels that each got.

#1 Fix Linux compilation
  BUILD_INSTRUCTIONS.md
  mp/src/fgdlib/gdvar.cpp
  mp/src/fgdlib/wckeyvalues.cpp
  mp/src/game/client/client_base.vpc
  mp/src/game/client/neo/game_controls/neo_teammenu.cpp
  mp/src/game/client/neo/ui/neo_hud_ammo.cpp
  mp/src/game/client/neo/ui/neo_hud_childelement.h
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.h
  mp/src/game/server/server_base.vpc
  mp/src/game/shared/inttostr.cpp
  mp/src/game/shared/inttostr.h
  mp/src/game/shared/neo/neo_mount_original.h
  mp/src/utils/vbsp/map.cpp
Labels: tooling

#3 Community Edition Changes Part 01: General bug fixes
  .gitignore
  mp/src/createallprojects.bat
  mp/src/creategameprojects
  mp/src/creategameprojects.bat
  mp/src/game/client/c_baseflex.cpp
  mp/src/game/client/c_colorcorrection.cpp
  mp/src/game/client/c_colorcorrectionvolume.cpp
  mp/src/game/client/client_neo.vpc
  mp/src/game/client/game_controls/vguitextwindow.cpp
  mp/src/game/client/vgui_video.cpp
  mp/src/game/client/view.cpp
  mp/src/game/server/ai_basenpc.cpp
  mp/src/game/server/baseflex.cpp
  mp/src/game/server/hl2/hl2_player.cpp
  mp/src/game/server/hl2/npc_combine.cpp
  mp/src/game/server/hl2/npc_combine.h
  mp/src/game/server/hl2/npc_combinedropship.cpp
  mp/src/game/server/server_neo.vpc
  mp/src/game/shared/hl2/hl_gamemovement.cpp
  mp/src/game/shared/physics_shared.cpp
  mp/src/public/bone_setup.cpp
  mp/src/public/sentence.cpp
  mp/src/public/tier1/utlbuffer.h
  mp/src/public/vphysics/collision_set.h
  mp/src/tier1/strtools.cpp
  mp/src/utils/vbsp/detail.cpp
  mp/src/vpc_scripts/default.vgc
  mp/src/vpc_scripts/projects.vgc
Labels: external source

#5 Replace README with README.md, add server notes
  README
  README.md
  SERVER_INSTRUCTIONS.md
Labels: documentation

#6 Alternate team spawn and caps based on round number
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/neo/neo_ghost_cap_point.cpp
  mp/src/game/shared/neo/neo_ghost_cap_point.h
Labels: enhancement

#7 Fix sticky fire on milso, zr68l, m41l, m41s, and srs (blocked from firing bullets bug)
  mp/src/game/shared/neo/weapons/weapon_m41l.cpp
  mp/src/game/shared/neo/weapons/weapon_m41s.cpp
  mp/src/game/shared/neo/weapons/weapon_milso.cpp
  mp/src/game/shared/neo/weapons/weapon_srs.cpp
  mp/src/game/shared/neo/weapons/weapon_zr68l.cpp
Labels: bug

#11 Cap point - Show distance marker
  mp/src/game/shared/neo/neo_ghost_cap_point.h
  mp/src/game/shared/shareddefs.h
Labels: enhancement

#12 Fix max player being set to 16, should be MAX_PLAYER
  mp/src/game/server/hl2mp/hl2mp_gameinterface.cpp
Labels: bug

#13 Hold to aim - cvar: neo_aim_hold
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
Labels: enhancement

#14 Toggle to lean - cvar: neo_lean_toggle
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
Labels: enhancement

#15 Separate AUX and cloak/optical camo + OG:NT drain/recover parity
  mp/src/game/client/hl2/c_hl2_playerlocaldata.cpp
  mp/src/game/client/hl2/c_hl2_playerlocaldata.h
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/server/hl2/hl2_player.cpp
  mp/src/game/server/hl2/hl2_playerlocaldata.cpp
  mp/src/game/server/hl2/hl2_playerlocaldata.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_player_shared.h
Labels: enhancement

#16 Loud round end music fix attempt
  mp/src/game/shared/neo/neo_gamerules.cpp
Labels: bug

#17 Remove player collision
  mp/src/game/shared/neo/neo_gamerules.cpp
Labels: enhancement

#20 Ghost beacon - Fix drop not dropping hud, fix dead players showing up
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/shared/neo/weapons/weapon_ghost.cpp
Labels: bug

#22 Ghost marker - Team coloring, fix darken screen/visuals, improve hud
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/neo/ui/neo_hud_compass.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
Labels: enhancement

#23 CTG Status - Implement warmup round
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.h
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
Labels: enhancement

#9 Add status (Dead/Alive) to the scoreboard
  mp/src/game/client/hl2mp/ui/hl2mpclientscoreboard.cpp
  mp/src/game/client/hl2mp/ui/hl2mpclientscoreboard.h
  mp/src/game/client/neo/ui/neo_scoreboard.cpp
  mp/src/game/client/neo/ui/neo_scoreboard.h
Labels: enhancement

#10 Scoreboard - Add team header text, styling closer to OG:NT
  mp/src/game/client/c_playerresource.cpp
  mp/src/game/client/neo/ui/neo_scoreboard.cpp
Labels: enhancement

#25 Hide knife visibility when dead
  mp/src/game/shared/neo/weapons/weapon_knife.cpp
  mp/src/game/shared/neo/weapons/weapon_knife.h
Labels: bug

#186 Fix NULL dereference on pCurrent (SwitchToNextBestWeapon)
  mp/src/game/shared/basecombatcharacter_shared.cpp
Labels: bug

#188 Fix CE change merge regarding zoom
  mp/src/game/client/view.cpp
Labels: bug

#189 Fix some merge taking out cloak update lines
  mp/src/game/server/neo/neo_player.cpp
Labels: bug

#190 override -> OVERRIDE fix for Linux compile
  mp/src/game/server/hl2mp/hl2mp_player.h
Labels: bug

#24 Ghost beacon - Startup visibility delay + Restore sound
  mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h
  mp/src/game/shared/neo/weapons/weapon_ghost.cpp
  mp/src/game/shared/neo/weapons/weapon_ghost.h
Labels: enhancement

#192 Disable spawning HL2 guns
  mp/game/neo/scripts/kb_act.lst
  mp/src/game/client/client_neo.vpc
  mp/src/game/client/hl2/c_weapon__stubs_hl2.cpp
  mp/src/game/server/basecombatcharacter.cpp
  mp/src/game/server/func_break.cpp
  mp/src/game/server/hl2/ai_allymanager.cpp
  mp/src/game/server/hl2/hl2_player.cpp
  mp/src/game/server/hl2/npc_citizen17.cpp
  mp/src/game/server/hl2/npc_combinegunship.cpp
  mp/src/game/server/hl2/npc_scanner.cpp
  mp/src/game/server/hl2/npc_spotlight.cpp
  mp/src/game/server/hl2/weapon_crowbar.cpp
  mp/src/game/server/player.cpp
  mp/src/game/server/server_neo.vpc
  mp/src/game/shared/hl2mp/weapon_stunstick.cpp
Labels: bug

#198 Slow down on land
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/server/neo/neo_player.cpp
Labels: bug

#197 Further HUD Customisation
  mp/src/game/client/neo/ui/neo_hud_ammo.cpp
  mp/src/game/client/neo/ui/neo_hud_ammo.h
  mp/src/game/client/neo/ui/neo_hud_childelement.cpp
  mp/src/game/client/neo/ui/neo_hud_childelement.h
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h
Labels: bug

#232 Configurable FOV/Field of view, new convar: neo_fov
  mp/src/game/client/c_baseplayer.h
  mp/src/game/client/hl2/hl2_clientmode.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/view.cpp
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/server/player.cpp
  mp/src/game/server/player.h
  mp/src/game/shared/baseplayer_shared.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/shareddefs.h
Labels: enhancement

#239 Separate offset from normal vs zoomed in + gradual viewmodel ADS switch
  mp/game/neo/scripts/weapon_aa13.txt
  mp/game/neo/scripts/weapon_ghost.txt
  mp/game/neo/scripts/weapon_grenade.txt
  mp/game/neo/scripts/weapon_jitte.txt
  mp/game/neo/scripts/weapon_jittescoped.txt
  mp/game/neo/scripts/weapon_knife.txt
  mp/game/neo/scripts/weapon_kyla.txt
  mp/game/neo/scripts/weapon_m41.txt
  mp/game/neo/scripts/weapon_m41l.txt
  mp/game/neo/scripts/weapon_m41s.txt
  mp/game/neo/scripts/weapon_milso.txt
  mp/game/neo/scripts/weapon_mpn.txt
  mp/game/neo/scripts/weapon_mpn_unsilenced.txt
  mp/game/neo/scripts/weapon_mx.txt
  mp/game/neo/scripts/weapon_mx_silenced.txt
  mp/game/neo/scripts/weapon_pbk56s.txt
  mp/game/neo/scripts/weapon_pz.txt
  mp/game/neo/scripts/weapon_remotedet.txt
  mp/game/neo/scripts/weapon_smac.txt
  mp/game/neo/scripts/weapon_smokegrenade.txt
  mp/game/neo/scripts/weapon_srm.txt
  mp/game/neo/scripts/weapon_srm_s.txt
  mp/game/neo/scripts/weapon_srs.txt
  mp/game/neo/scripts/weapon_supa7.txt
  mp/game/neo/scripts/weapon_tachi.txt
  mp/game/neo/scripts/weapon_zr68c.txt
  mp/game/neo/scripts/weapon_zr68l.txt
  mp/game/neo/scripts/weapon_zr68s.txt
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.h
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/hl2mp/hl2mp_weapon_parse.cpp
  mp/src/game/shared/neo/neo_player_shared.h
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
  mp/src/game/shared/neo/neo_predicted_viewmodel.h
Labels: Gameplay

#243 Team switching - Make it available as server convar, change defaults
  mp/src/game/server/neo/neo_player.cpp
Labels: Gameplay

#250 Revert accidental code deletion - Ghost marker should be red on enemy
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.h
Labels: bug

#255 Supa7 - Fix animation usage between slug and primary
  mp/src/game/shared/neo/weapons/weapon_supa7.cpp
Labels: Animations

#268 Fix vgui button issue
  mp/src/CMakeLists.txt
  mp/src/game/client/CMakeLists.txt
  mp/src/game/server/CMakeLists.txt
  mp/src/materialsystem/stdshaders/CMakeLists.txt
Labels: bug, tooling, VGUI

#258 Damage + hits + killer info on death/round end
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/hl2/hl2_usermessages.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
Labels: General Plugin

#264 Implement round limit, early win, match point indicator, and sudden death
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
Labels: enhancement, Competetive Plugin

#262 Merge into a single README.md, update CONTRIBUTING.md, new cmake + qtcreator instructions
  BUILD_INSTRUCTIONS.md
  CONTRIBUTING.md
  README.md
  SERVER_INSTRUCTIONS.md
  Shader_Authoring.md
Labels: documentation

#304 Create _srv.so symlinks
  mp/src/game/client/CMakeLists.txt
  mp/src/game/server/CMakeLists.txt
Labels: tooling

#305 Remove inttostr
  mp/src/game/client/CMakeLists.txt
  mp/src/game/client/client_base.vpc
  mp/src/game/client/neo/ui/neo_hud_ammo.cpp
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/server/CMakeLists.txt
  mp/src/game/server/server_base.vpc
  mp/src/game/shared/inttostr.cpp
  mp/src/game/shared/inttostr.h
  mp/src/game/shared/neo/neo_mount_original.h
Labels: bug

#303 Raise minimum C++ standard to C++20
  CONTRIBUTING.md
  README.md
  mp/src/CMakeLists.txt
  mp/src/game/client/c_baseentity.h
  mp/src/game/client/clientshadowmgr.cpp
  mp/src/game/client/hud_closecaption.cpp
  mp/src/game/client/hud_squadstatus.cpp
  mp/src/game/client/particlemgr.cpp
  mp/src/game/client/text_message.cpp
  mp/src/game/server/CommentarySystem.cpp
  mp/src/game/server/ai_behavior_lead.cpp
  mp/src/game/server/ai_behavior_lead.h
  mp/src/game/server/ai_playerally.cpp
  mp/src/game/server/ai_playerally.h
  mp/src/game/server/ai_speech.cpp
  mp/src/game/server/ai_speech.h
  mp/src/game/server/baseentity.cpp
  mp/src/game/server/baseentity.h
  mp/src/game/server/basemultiplayerplayer.cpp
  mp/src/game/server/basemultiplayerplayer.h
  mp/src/game/server/explode.cpp
  mp/src/game/server/hl2/ai_behavior_actbusy.cpp
  mp/src/game/server/hl2/combine_mine.cpp
  mp/src/game/server/hl2/npc_basescanner.h
  mp/src/game/server/hl2/npc_breen.cpp
  mp/src/game/server/hl2/npc_crow.cpp
  mp/src/game/server/hl2/npc_eli.cpp
  mp/src/game/server/hl2/npc_kleiner.cpp
  mp/src/game/server/hl2/npc_playercompanion.cpp
  mp/src/game/server/hl2/npc_playercompanion.h
  mp/src/game/server/hl2/npc_scanner.cpp
  mp/src/game/server/hl2/npc_scanner.h
  mp/src/game/server/hl2/npc_vortigaunt_episodic.cpp
  mp/src/game/server/hl2/prop_thumper.cpp
  mp/src/game/server/hltvdirector.h
  mp/src/game/server/nav_merge.cpp
  mp/src/game/server/npc_talker.cpp
  mp/src/game/server/npc_talker.h
  mp/src/game/server/sceneentity.cpp
  mp/src/game/server/textstatsmgr.cpp
  mp/src/game/server/textstatsmgr.h
  mp/src/game/shared/SoundEmitterSystem.cpp
  mp/src/game/shared/basecombatweapon_shared.cpp
  mp/src/game/shared/hl2mp/hl2mp_gamerules.cpp
  mp/src/game/shared/util_shared.cpp
  mp/src/game/shared/util_shared.h
  mp/src/public/dt_utlvector_send.cpp
  mp/src/public/dt_utlvector_send.h
  mp/src/public/keyframe/keyframe.cpp
  mp/src/public/particles/particles.h
  mp/src/public/studio.cpp
  mp/src/public/tier0/threadtools.h
  mp/src/public/tier1/UtlSortVector.h
  mp/src/public/tier1/UtlStringMap.h
  mp/src/public/tier1/datamanager.h
  mp/src/public/vgui_controls/Panel.h
  mp/src/tier1/checksum_md5.cpp
  mp/src/vgui2/vgui_controls/BuildGroup.cpp
  mp/src/vgui2/vgui_controls/Panel.cpp
  mp/src/vgui2/vgui_controls/PropertyPage.cpp
Labels: tooling, refactor

#311 Reduce compiler warnings
  mp/src/CMakeLists.txt
  mp/src/game/client/ViewConeImage.cpp
  mp/src/game/client/c_effects.cpp
  mp/src/game/client/c_sceneentity.cpp
  mp/src/game/client/c_testtraceline.cpp
  mp/src/game/client/clientleafsystem.cpp
  mp/src/game/client/entity_client_tools.cpp
  mp/src/game/client/fx_impact.cpp
  mp/src/game/client/hl2mp/hud_deathnotice.cpp
  mp/src/game/client/neo/game_controls/neo_classmenu.cpp
  mp/src/game/client/neo/game_controls/neo_loadoutmenu.cpp
  mp/src/game/client/neo/game_controls/neo_teammenu.cpp
  mp/src/game/client/neo/ui/neo_hud_ammo.cpp
  mp/src/game/client/neo/ui/neo_hud_elements.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.h
  mp/src/game/client/vgui_bitmapimage.cpp
  mp/src/game/client/vgui_loadingdiscpanel.cpp
  mp/src/game/client/vgui_messagechars.cpp
  mp/src/game/client/vgui_video.cpp
  mp/src/game/client/vgui_video_player.cpp
  mp/src/game/client/viewrender.cpp
  mp/src/game/server/ai_behavior_lead.cpp
  mp/src/game/server/ai_memory.cpp
  mp/src/game/server/ai_memory.h
  mp/src/game/server/ai_network.h
  mp/src/game/server/ai_scriptconditions.cpp
  mp/src/game/server/hl2/npc_strider.cpp
  mp/src/game/server/hl2/npc_strider.h
  mp/src/game/server/nav_mesh.h
  mp/src/game/server/neo/neo_model_manager.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/shared/baseplayer_shared.cpp
  mp/src/game/shared/death_pose.h
  mp/src/game/shared/effect_dispatch_data.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_ghost_cap_point.cpp
  mp/src/game/shared/neo/neo_player_shared.h
  mp/src/game/shared/particle_parse.cpp
  mp/src/game/shared/soundenvelope.cpp
  mp/src/mathlib/sseconst.cpp
  mp/src/public/UtlCachedFileData.h
  mp/src/public/bitmap/imageformat.h
  mp/src/public/engine/ivmodelinfo.h
  mp/src/public/ispatialpartition.h
  mp/src/public/keyframe/keyframe.h
  mp/src/public/mathlib/vector.h
  mp/src/public/particles/particles.h
  mp/src/public/tier1/utlhashtable.h
  mp/src/public/tier1/utlsoacontainer.h
  mp/src/public/vgui_controls/BuildGroup.h
  mp/src/public/vgui_controls/FocusNavGroup.h
  mp/src/public/vgui_controls/Tooltip.h
  mp/src/vgui2/vgui_controls/Splitter.cpp
Labels: tooling, refactor

#306 Prevent supports from being given a knife
  mp/src/game/server/neo/neo_player.cpp
Labels: Gameplay
