Repository NeotokyoRebuild/neo, pull requests merged in 2024-06, with the labels that each got.

#317 Knife - Refactor to use CNEOBaseCombatWeapon, use sprint animation when sprinting
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/shared/neo/weapons/weapon_grenade.cpp
  mp/src/game/shared/neo/weapons/weapon_knife.cpp
  mp/src/game/shared/neo/weapons/weapon_knife.h
  mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
Labels: refactor, Gunplay, Animations

#319 Center text use NT font
  mp/src/game/client/vgui_centerstringpanel.cpp
Labels: VGUI

#320 Compass HUD visual closer to OG:NT Styling + HudLayout.res customization
  mp/game/neo/scripts/HudLayout.res
  mp/src/game/client/neo/ui/neo_hud_childelement.cpp
  mp/src/game/client/neo/ui/neo_hud_childelement.h
  mp/src/game/client/neo/ui/neo_hud_compass.cpp
  mp/src/game/client/neo/ui/neo_hud_compass.h
  mp/src/game/client/neo/ui/neo_hud_elements.cpp
Labels: VGUI

#266 Set custom player name, cl_fakenick = 0 to only use Steam name, postfix index duplicate names
  mp/game/neo/resource/NeoModEvents.res
  mp/src/game/client/c_playerresource.cpp
  mp/src/game/client/c_playerresource.h
  mp/src/game/client/clientmode_shared.cpp
  mp/src/game/client/hud_basechat.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp
  mp/src/game/server/client.cpp
  mp/src/game/server/neo/neo_client.cpp
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/server/player_resource.cpp
  mp/src/game/server/player_resource.h
  mp/src/game/shared/gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
Labels: VGUI, Gameplay

#322 Fix cloak sound not giving sounds server side
  mp/src/game/server/neo/neo_player.cpp
Labels: Gameplay

#326 Fix exit crash around m_pGameEvent in gHud situation
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/ui/neo_hud_elements.cpp
  mp/src/game/client/neo/ui/neo_hud_elements.h
  mp/src/game/client/neo/ui/neo_hud_game_event.cpp
  mp/src/game/client/neo/ui/neo_hud_game_event.h
Labels: bug

#346 Fix docs command typo
  CONTRIBUTING.md
Labels: documentation

#344 Fix missing HudLayout.res defines (HudMenu/HudRadio) - Fixes attacker info missing
  mp/game/neo/scripts/HudLayout.res
Labels: bug

#348 Fix SpectatorGUI memory corruption crash
  mp/src/game/client/game_controls/SpectatorGUI.cpp
  mp/src/game/client/game_controls/spectatorgui.h
Labels: bug

#349 Generate build date + hash to the main menu and neo_version on building the project
  .gitignore
  mp/game/neo/resource/GameMenu.preproc.res
  mp/src/cmake/build_info.cmake
  mp/src/cmake/utils.cmake
  mp/src/game/client/CMakeLists.txt
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h
  mp/src/game/server/CMakeLists.txt
  mp/src/game/shared/neo/neo_version.cpp
  mp/src/game/shared/neo/neo_version_info.preproc.h
Labels: tooling

#376 Added Instructions for "Dedicated Server on Windows"
  README.md
Labels: documentation

#352 Change ADS toggle from on-release to on-press and sprint related bug fixes
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/server/neo/neo_player.cpp
Labels: Gameplay, General Plugin, New Changes for Reviewers

#353 Grenades shouldn't collide with players
  mp/src/game/shared/neo/neo_gamerules.cpp
Labels: Gunplay

#351 GitHub issues + pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, New Changes for Reviewers

#386 Document SourceMod require ShowMenu whitelist for plugins to show menus
  README.md
Labels: documentation

#360 Fix buggy viewmodel ADS change transition on dedicated servers
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.h
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
  mp/src/game/shared/neo/neo_predicted_viewmodel.h
Labels: bug

#374 Player XP restored within per map session
  mp/src/game/server/neo/neo_client.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
Labels: New Changes for Reviewers

#392 Use [[maybe_unused]]
  mp/src/game/server/MaterialModifyControl.cpp
  mp/src/game/server/bmodels.cpp
  mp/src/game/server/soundscape_system.cpp
  mp/src/game/shared/igamesystem.cpp
  mp/src/game/shared/neo/weapons/weapon_knife.cpp
  mp/src/mathlib/noisedata.h
  mp/src/mathlib/ssenoise.cpp
  mp/src/public/datamodel/dmehandle.h
  mp/src/public/shaderlib/cshader.h
  mp/src/public/tier0/basetypes.h
  mp/src/public/tier0/commonmacros.h
  mp/src/vgui2/vgui_controls/FileOpenDialog.cpp
  mp/src/vgui2/vgui_controls/Panel.cpp
  mp/src/vgui2/vgui_controls/PerforceFileList.cpp
Labels: refactor

#361 Update .gitignore
  .gitignore
Labels: tooling

#358 Make zoom speed close to OG:NT
  mp/src/game/shared/neo/neo_player_shared.h
Labels: Gameplay

#379 Return mouse back to camera on closing VGUI dialog
  mp/src/game/client/neo/game_controls/neo_classmenu.cpp
  mp/src/game/client/neo/game_controls/neo_classmenu.h
  mp/src/game/client/neo/game_controls/neo_loadoutmenu.cpp
  mp/src/game/client/neo/game_controls/neo_loadoutmenu.h
  mp/src/game/client/neo/game_controls/neo_teammenu.cpp
  mp/src/game/client/neo/game_controls/neo_teammenu.h
Labels: bug

#381 Client side MOTD control
  mp/src/game/client/clientmode_shared.h
  mp/src/game/client/game_controls/vguitextwindow.cpp
  mp/src/game/client/game_controls/vguitextwindow.h
  mp/src/game/server/neo/neo_client.cpp
Labels: VGUI

#391 Improve lean prediction
  mp/game/neo/scripts/kb_act.lst
  mp/src/game/client/in_main.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
  mp/src/game/shared/neo/neo_predicted_viewmodel.h
Labels: bug

#369 Replace neo_hud_elements to huds managing themselves
  mp/src/game/client/CMakeLists.txt
  mp/src/game/client/client_neo.vpc
  mp/src/game/client/game_controls/baseviewport.cpp
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
  mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp
  mp/src/game/client/hl2mp/hud_deathnotice.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/neo/ui/neo_hud_ammo.cpp
  mp/src/game/client/neo/ui/neo_hud_ammo.h
  mp/src/game/client/neo/ui/neo_hud_childelement.cpp
  mp/src/game/client/neo/ui/neo_hud_childelement.h
  mp/src/game/client/neo/ui/neo_hud_compass.cpp
  mp/src/game/client/neo/ui/neo_hud_compass.h
  mp/src/game/client/neo/ui/neo_hud_elements.cpp
  mp/src/game/client/neo/ui/neo_hud_elements.h
  mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/client/neo/ui/neo_hud_worldpos_marker.h
  mp/src/game/shared/viewport_panel_names.h
Labels: refactor

#388 Fix round state HUD player's team mismatch, and allow spectator "team" to see all healthbars
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.cpp
  mp/src/game/client/neo/ui/neo_hud_round_state.h
  mp/src/game/shared/neo/neo_gamerules.h
Labels: bug

#390 Default to not relay player's neo_fov to 1st person specator, add ADS FOV transition for spec, use script AimFov
  mp/game/neo/scripts/weapon_jittescoped.txt
  mp/game/neo/scripts/weapon_tachi.txt
  mp/src/game/client/c_baseplayer.cpp
  mp/src/game/client/c_baseplayer.h
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/view.cpp
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/server/player.cpp
  mp/src/game/server/player.h
  mp/src/game/shared/baseplayer_shared.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/neo_player_shared.h
  mp/src/game/shared/shareddefs.h
Labels: enhancement, New Changes for Reviewers

#399 Disable HDR while using vision mode
  mp/src/game/client/viewpostprocess.cpp
Labels: bug

#404 Backstabs
  mp/src/game/shared/neo/weapons/weapon_knife.cpp
Labels: bug

#408 Update default key binds & descriptions
  mp/game/neo/cfg/legacybinds.cfg
  mp/game/neo/scripts/kb_act.lst
  mp/game/neo/scripts/kb_def.lst
Labels: Gameplay

#412 Fix cursor stuck after disconnect while in menu then reconnect
  mp/src/game/client/neo/c_neo_player.cpp
Labels: bug

#403 Blood Impact visual closer to og
  mp/src/game/client/fx_blood.cpp
Labels: bug
