Repository NeotokyoRebuild/neo, pull requests merged in 2024-10, with the labels that each got.

#689 Fix collision (knife, bullet, blood) by limiting NT collide check to only movement
  mp/src/game/shared/gamemovement.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/util_shared.cpp
  mp/src/game/shared/util_shared.h
Labels: bug, URGENT

#696 CI - Upload on tagged/release
  .github/workflows/cibuild.yml
Labels: CI

#562 Startup Errors in console
  mp/game/neo/resource/neo_english.txt
  mp/game/neo/resource/spectatormenu.res
  mp/game/neo/scripts/HudLayout.res
  mp/game/neo/scripts/game_sounds_weapons.txt
  mp/game/neo/scripts/vgui_screens.txt
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
  mp/src/game/shared/hl2mp/hl2mp_player_shared.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_player_shared.cpp
  mp/src/game/shared/neo/weapons/weapon_grenade.cpp
  mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
Labels: New Changes for Reviewers, Changes in neoAssets

#685 Motion Thermal Shader changes
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
  mp/src/materialsystem/stdshaders/CMakeLists.txt
  mp/src/materialsystem/stdshaders/Neo_MotionVision_Shader_Pass1.cpp
  mp/src/materialsystem/stdshaders/Neo_ThermalVision.cpp
  mp/src/materialsystem/stdshaders/fxctmp9/neo_motion_model_ps20b.inc
  mp/src/materialsystem/stdshaders/fxctmp9/neo_motion_model_vs20.inc
  mp/src/materialsystem/stdshaders/fxctmp9/neo_thermal_model_ps20b.inc
  mp/src/materialsystem/stdshaders/fxctmp9/neo_thermal_model_vs20.inc
  mp/src/materialsystem/stdshaders/neo_motion_model_dx9.cpp
  mp/src/materialsystem/stdshaders/neo_motion_model_dx9_helper.cpp
  mp/src/materialsystem/stdshaders/neo_motion_model_dx9_helper.h
  mp/src/materialsystem/stdshaders/neo_motion_model_ps20b.fxc
  mp/src/materialsystem/stdshaders/neo_motion_model_vs20.fxc
  mp/src/materialsystem/stdshaders/neo_motionvision_pass1_ps30.fxc
  mp/src/materialsystem/stdshaders/neo_motionvision_pass2_ps30.fxc
  mp/src/materialsystem/stdshaders/neo_thermal_model_dx9.cpp
  mp/src/materialsystem/stdshaders/neo_thermal_model_dx9_helper.cpp
  mp/src/materialsystem/stdshaders/neo_thermal_model_dx9_helper.h
  mp/src/materialsystem/stdshaders/neo_thermal_model_ps20b.fxc
  mp/src/materialsystem/stdshaders/neo_thermal_model_vs20.fxc
  mp/src/materialsystem/stdshaders/stdshader_dx9_20b.txt
Labels: Changes in neoAssets

#578 Player outlines in spectator mode
  mp/src/CMakeLists.txt
  mp/src/game/client/c_basecombatcharacter.cpp
  mp/src/game/client/c_basecombatcharacter.h
  mp/src/game/client/c_team_train_watcher.cpp
  mp/src/game/client/clientmode_shared.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp
  mp/src/game/server/basecombatcharacter.cpp
  mp/src/game/server/basecombatcharacter.h
  mp/src/game/shared/neo/neo_gamerules.h
Labels: Changes in neoAssets

#700 Fix possible crash on exit - NeoLoading
  mp/src/game/client/clientmode_shared.cpp
Labels: bug

#693 Refract cloak
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
  mp/src/game/shared/neo/neo_predicted_viewmodel.h
  mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
  mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
Labels: Gameplay, Changes in neoAssets

#709 Revert "team based blocking and options"
  mp/src/game/shared/gamemovement.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/util_shared.cpp
  mp/src/game/shared/util_shared.h
Labels: bug, URGENT

#718 Damage/killer info duration 60s->10s + Dismiss forever
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_gamerules.cpp
Labels: New Changes for Reviewers

#730 Do not delete g_pNeoLoading ourselves, probably already done by engine
  mp/src/game/client/clientmode_shared.cpp
Labels: bug

#746 Fix mis-match between round start and current spawning
  mp/src/game/shared/neo/neo_gamerules.cpp
Labels: bug, URGENT

#748 Damge/penetration script corrections
  mp/game/neo/scripts/weapon_srm.txt
  mp/game/neo/scripts/weapon_srm_s.txt
  mp/game/neo/scripts/weapon_zr68c.txt
Labels: Gunplay, URGENT

#753 NeoUI Settings - call mat_savechanges on save
  mp/src/game/client/neo/ui/neo_root_settings.cpp
Labels: bug

#762 Rangefinder HUD
  mp/src/game/client/neo/ui/neo_hud_compass.cpp
  mp/src/game/client/neo/ui/neo_hud_compass.h
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
Labels: New Changes for Reviewers
