Repository NeotokyoRebuild/neo, pull requests merged in 2024-09, with the labels that each got.

#555 Mirror team damage, Kick on team kill + damage accumulated threshold
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
Labels: New Changes for Reviewers

#476 Ghost - Refactor away from player to HUD/Gamerule, PVS for smoother visual
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/client/neo/c_neo_player.h
  mp/src/game/client/neo/ui/neo_hud_childelement.h
  mp/src/game/client/neo/ui/neo_hud_compass.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.h
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_gamerules.h
  mp/src/game/shared/neo/weapons/weapon_ghost.cpp
  mp/src/game/shared/neo/weapons/weapon_ghost.h
Labels: refactor

#557 Don't drain AUX in underwater, don't tie drowning to AUX in underwater
  mp/src/game/server/hl2/hl2_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/server/player.cpp
Labels: New Changes for Reviewers

#554 Root menu (IMGUI) - Replace settings, serverlist + new game panels
  mp/game/neo/gameinfo.txt
  mp/game/neo/resource/ClientScheme.res
  mp/src/game/client/CMakeLists.txt
  mp/src/game/client/cdll_client_int.cpp
  mp/src/game/client/neo/ui/IOverrideInterface.h
  mp/src/game/client/neo/ui/OverrideInterface.cpp
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root.h
  mp/src/game/client/neo/ui/neo_root_serverbrowser.cpp
  mp/src/game/client/neo/ui/neo_root_serverbrowser.h
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
  mp/src/game/client/neo/ui/neo_ui.cpp
  mp/src/game/client/neo/ui/neo_ui.h
  mp/src/game/client/vgui_fpspanel.cpp
  mp/src/game/client/vgui_int.cpp
  mp/src/game/shared/neo/neo_gamerules.cpp
  mp/src/game/shared/neo/neo_version_info.cpp.in
  mp/src/game/shared/neo/neo_version_info.h
  mp/src/vgui2/vgui_controls/ScrollBarSlider.cpp
Labels: enhancement, VGUI

#600 NeoUI - Change normal font to from neuropol2 to green mountain
  mp/game/neo/resource/ClientScheme.res
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_ui.cpp
  mp/src/game/client/neo/ui/neo_ui.h
Labels: Minor release priority

#573 Supa7 use Slugs with no primary ammo
  mp/src/game/shared/neo/weapons/weapon_supa7.cpp
Labels: Minor release priority

#595 Fix crash at Neo menu constructors
  mp/src/game/client/neo/game_controls/neo_classmenu.h
  mp/src/game/client/neo/game_controls/neo_loadoutmenu.h
  mp/src/game/client/neo/game_controls/neo_teammenu.h
Labels: bug, Minor release priority

#594 Add extra guards against segfault
  mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
Labels: bug, Minor release priority

#611 Fix issue where spread would be halved.
  mp/src/game/shared/neo/neo_shot_manipulator.cpp
  mp/src/game/shared/neo/neo_shot_manipulator.h
Labels: Minor release priority

#564 Sprinting in water, crouch sprinting, speeds touchup
  mp/src/game/client/hl2mp/c_hl2mp_player.cpp
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/server/hl2/hl2_player.cpp
  mp/src/game/server/neo/neo_player.cpp
Labels: Minor release priority

#572 SRS Spawns with a round in the chamber
  mp/src/game/shared/neo/weapons/weapon_srs.cpp
Labels: Minor release priority

#599 Settings changed popup - Replace discard with cancel
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_ui.cpp
  mp/src/game/client/neo/ui/neo_ui.h
Labels: Minor release priority

#597 Fix -neopath for Linux
  README.md
  mp/src/game/shared/neo/neo_mount_original.h
Labels: bug, Minor release priority

#589 Enforce con_enable 1 and multiple fixes for keybind handling
  mp/src/game/client/cdll_client_int.cpp
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root_settings.cpp
Labels: bug, Minor release priority

#598 Revert "replace weapon_switch with ClientCommand (#570)"
  mp/src/game/server/neo/neo_player.cpp
Labels: bug, Minor release priority

#545 Grenades falling through floor, dropped weapon mechanics
  mp/game/neo/scripts/weapon_knife.txt
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/weapons/weapon_grenade.cpp
  mp/src/game/shared/neo/weapons/weapon_grenade.h
  mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
  mp/src/game/shared/neo/weapons/weapon_smokegrenade.h
  mp/src/game/shared/weapon_parse.cpp
  mp/src/game/shared/weapon_parse.h
Labels: Minor release priority

#574 Supa 7 Slug Damage
  mp/src/game/server/hl2mp/hl2mp_player.cpp
Labels: Minor release priority

#617 Recon aux regen rate halved when sprinting
  mp/src/game/server/hl2/hl2_player.cpp
Labels: Minor release priority

#619 Font at higher resolutions too bright
  mp/game/neo/resource/ClientScheme.res
Labels: Minor release priority

#580 Fetch news/blog from website, use latest git tag for version
  .github/workflows/cibuild.yml
  .gitignore
  mp/src/CMakeLists.txt
  mp/src/cmake/build_info.cmake
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root.h
  mp/src/game/client/neo/ui/neo_ui.cpp
  mp/src/game/client/neo/ui/neo_ui.h
  mp/src/game/shared/neo/neo_version_info.cpp.in
  mp/src/game/shared/neo/neo_version_info.h
Labels: New Changes for Reviewers

#636 NeoUI - Console toggle key rebind, intended for non-` key layouts
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
Labels: bug, Minor release priority

#491 Cleaner scope
  mp/src/game/client/hud_crosshair.cpp
Labels: New Changes for Reviewers, Minor release priority, Changes in neoAssets

#649 Throwables origin clipping into ground workaround
  mp/src/game/shared/neo/weapons/weapon_detpack.cpp
  mp/src/game/shared/neo/weapons/weapon_grenade.cpp
  mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
Labels: Minor release priority

#648 NeoUI - Settings add reset to default button + Fix settings applying
  mp/game/neo/scripts/kb_def.lst
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root.h
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
Labels: bug, Minor release priority

#610 Spatial reload sounds, stop reload sounds when dropping or switching weapon, fix for weapons reloading on the floor
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/shared/basecombatweapon_shared.cpp
Labels: New Changes for Reviewers
