Repository NeotokyoRebuild/neo, pull requests merged in 2025-03, with the labels that each got.

#852 toolsblockbullets uses surfaceprop to block bullets instead of thickness of brush
  game/neo/scripts/surfaceproperties_manifest.txt
  game/neo/scripts/surfaceproperties_ntre.txt
  src/game/shared/baseentity_shared.cpp
Labels: Changes in neoAssets

#904 Tutorial - Hints
  game/neo/resource/ClientScheme.res
  game/neo/scripts/HudLayout.res
  src/game/client/CMakeLists.txt
  src/game/client/neo/c_neo_message.cpp
  src/game/client/neo/c_neo_message.h
  src/game/client/neo/ui/neo_hud_message.cpp
  src/game/client/neo/ui/neo_hud_message.h
  src/game/server/CMakeLists.txt
  src/game/server/neo/neo_message.cpp
  src/game/server/neo/neo_message.h
Labels: VGUI, Changes in neoAssets, Mapping, Tutorial

#962 Fix line endings in new server browser
  src/game/client/neo/ui/neo_root_serverbrowser.cpp
Labels: VGUI

#954 Tutorial - Dummy NPC Again
  src/game/client/CMakeLists.txt
  src/game/client/neo/c_neo_npc_dummy.cpp
  src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
  src/game/server/CMakeLists.txt
  src/game/server/neo/neo_npc_dummy.cpp
  src/game/shared/neo/neo_gamerules.cpp
  src/game/shared/neo/neo_gamerules.h
Labels: enhancement, Mapping, Tutorial

#967 Movement & weapon scaling parity
  src/game/client/neo/c_neo_player.cpp
  src/game/client/neo/c_neo_player.h
  src/game/server/neo/neo_player.cpp
  src/game/server/neo/neo_player.h
  src/game/shared/neo/neo_player_shared.h
  src/game/shared/neo/weapons/weapon_aa13.h
  src/game/shared/neo/weapons/weapon_detpack.h
  src/game/shared/neo/weapons/weapon_ghost.h
  src/game/shared/neo/weapons/weapon_grenade.h
  src/game/shared/neo/weapons/weapon_jitte.h
  src/game/shared/neo/weapons/weapon_jittes.h
  src/game/shared/neo/weapons/weapon_knife.h
  src/game/shared/neo/weapons/weapon_kyla.h
  src/game/shared/neo/weapons/weapon_m41.h
  src/game/shared/neo/weapons/weapon_m41l.h
  src/game/shared/neo/weapons/weapon_m41s.h
  src/game/shared/neo/weapons/weapon_milso.h
  src/game/shared/neo/weapons/weapon_mpn.h
  src/game/shared/neo/weapons/weapon_mpns.h
  src/game/shared/neo/weapons/weapon_mx.h
  src/game/shared/neo/weapons/weapon_mxs.h
  src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
  src/game/shared/neo/weapons/weapon_pbk56s.h
  src/game/shared/neo/weapons/weapon_pz.h
  src/game/shared/neo/weapons/weapon_smac.h
  src/game/shared/neo/weapons/weapon_smokegrenade.h
  src/game/shared/neo/weapons/weapon_srm.h
  src/game/shared/neo/weapons/weapon_srms.h
  src/game/shared/neo/weapons/weapon_srs.h
  src/game/shared/neo/weapons/weapon_supa7.h
  src/game/shared/neo/weapons/weapon_tachi.h
  src/game/shared/neo/weapons/weapon_zr68c.h
  src/game/shared/neo/weapons/weapon_zr68l.h
  src/game/shared/neo/weapons/weapon_zr68s.h
Labels: Movement, Gameplay

#956 Empty and Story gamemodes, game type settings change, ability to set default player options and hide player hud elements
  src/game/client/hud_basechat.cpp
  src/game/client/neo/c_neo_player.cpp
  src/game/client/neo/game_controls/neo_classmenu.cpp
  src/game/client/neo/game_controls/neo_classmenu.h
  src/game/client/neo/game_controls/neo_loadoutmenu.cpp
  src/game/client/neo/game_controls/neo_teammenu.cpp
  src/game/client/neo/game_controls/neo_teammenu.h
  src/game/client/neo/ui/neo_hud_ammo.cpp
  src/game/client/neo/ui/neo_hud_childelement.h
  src/game/client/neo/ui/neo_hud_compass.cpp
  src/game/client/neo/ui/neo_hud_crosshair.cpp
  src/game/client/neo/ui/neo_hud_damage_indicator.cpp
  src/game/client/neo/ui/neo_hud_friendly_marker.cpp
  src/game/client/neo/ui/neo_hud_game_event.cpp
  src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
  src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp
  src/game/client/neo/ui/neo_hud_ghost_marker.cpp
  src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp
  src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
  src/game/client/neo/ui/neo_hud_round_state.cpp
  src/game/client/neo/ui/neo_hud_worldpos_marker.cpp
  src/game/client/neo/ui/neo_scoreboard.cpp
  src/game/server/hl2mp/hl2mp_player.cpp
  src/game/server/neo/neo_client.cpp
  src/game/server/neo/neo_game_config.cpp
  src/game/server/neo/neo_game_config.h
  src/game/server/neo/neo_player.cpp
  src/game/server/player.cpp
  src/game/shared/neo/neo_gamerules.cpp
  src/game/shared/neo/neo_gamerules.h
Labels: Tutorial

#969 Add VScript support
  game/neo/scripts/vscripts/spawn_helper.nut
  game/neo/scripts/vscripts/vscript_server.nut
  src/game/server/point_template.cpp
  src/game/server/vscript_server.cpp
Labels: Build System, Mapping

#972 Tutorial resources
  game/neo/resource/neo_english.txt
  game/neo/scripts/game_sounds_physics.txt
  game/neo/scripts/soundscapes_manifest.txt
  game/neo/scripts/soundscapes_rebuild_tutorial.txt
  game/neo/scripts/surfaceproperties_ntre.txt
Labels: current WIP, Changes in neoAssets, Tutorial

#971 Adds buttons for launching the tutorial maps from the main menu
  game/neo/resource/neo_english.txt
  src/game/client/neo/ui/neo_root.cpp
  src/game/client/neo/ui/neo_root.h
Labels: Tutorial

#773 Sprays Importer/Gallery + fixed empty spray + NeoUI Texture/Image button + stb libraries + server-side disable spray
  src/game/client/CMakeLists.txt
  src/game/client/c_te_playerdecal.cpp
  src/game/client/neo/ui/neo_root.cpp
  src/game/client/neo/ui/neo_root.h
  src/game/client/neo/ui/neo_root_settings.cpp
  src/game/client/neo/ui/neo_ui.cpp
  src/game/client/neo/ui/neo_ui.h
  src/game/client/neo/ui/neo_utils.cpp
  src/game/client/neo/ui/neo_utils.h
  src/game/client/neo/vendor_impl.cpp
  src/game/shared/neo/neo_gamerules.cpp
  src/vendor/stb_dxt.h
  src/vendor/stb_image.h
  src/vendor/stb_image_resize2.h
Labels: Conflict

#983 Tutorial with keybinds
  game/neo/resource/ClientScheme.res
  game/neo/resource/neo_english.txt
  game/neo/scripts/HudLayout.res
  src/game/client/neo/ui/neo_root.cpp
Labels: Changes in neoAssets, Tutorial

#1011 Use sniper docker container
  .github/workflows/cibuild.yml
  src/CMakeLists.txt
  src/game/client/neo/neo_fixup_glshaders.cpp
  src/mathlib/CMakeLists.txt
Labels: Build System

#959 Update server instructions for 64-bits NT;RE
  README.md
  game/neo/steam.inf
  src/game/shared/neo/neo_gamerules.h
Labels: documentation

#1024 hotfix unable to spawn and tutorial crash
  src/game/client/neo/game_controls/neo_teammenu.cpp
  src/game/server/neo/neo_player.cpp
Labels: URGENT

#1025 weapon switching problem
  src/game/server/neo/neo_player.cpp
Labels: URGENT

#1012 Projected texture fixes
  src/game/client/c_env_projectedtexture.cpp
  src/game/client/clientshadowmgr.cpp
Labels: Mapping

#960 Extended Killfeed
  .gitignore
  game/neo/resource/ClientScheme.res
  game/neo/resource/NeoModEvents.res
  game/neo/scripts/HudLayout.res
  game/neo/scripts/weapon_aa13.txt
  game/neo/scripts/weapon_ghost.txt
  game/neo/scripts/weapon_grenade.txt
  game/neo/scripts/weapon_jitte.txt
  game/neo/scripts/weapon_jittescoped.txt
  game/neo/scripts/weapon_knife.txt
  game/neo/scripts/weapon_kyla.txt
  game/neo/scripts/weapon_m41.txt
  game/neo/scripts/weapon_m41l.txt
  game/neo/scripts/weapon_m41s.txt
  game/neo/scripts/weapon_milso.txt
  game/neo/scripts/weapon_mpn.txt
  game/neo/scripts/weapon_mpn_unsilenced.txt
  game/neo/scripts/weapon_mx.txt
  game/neo/scripts/weapon_mx_silenced.txt
  game/neo/scripts/weapon_pbk56s.txt
  game/neo/scripts/weapon_pz.txt
  game/neo/scripts/weapon_remotedet.txt
  game/neo/scripts/weapon_smac.txt
  game/neo/scripts/weapon_smokegrenade.txt
  game/neo/scripts/weapon_srm.txt
  game/neo/scripts/weapon_srm_s.txt
  game/neo/scripts/weapon_srs.txt
  game/neo/scripts/weapon_supa7.txt
  game/neo/scripts/weapon_tachi.txt
  game/neo/scripts/weapon_zr68c.txt
  game/neo/scripts/weapon_zr68l.txt
  game/neo/scripts/weapon_zr68s.txt
  src/game/client/CMakeLists.txt
  src/game/client/hud.cpp
  src/game/client/hud.h
  src/game/client/neo/c_neo_player.cpp
  src/game/client/neo/c_neo_player.h
  src/game/client/neo/ui/neo_hud_deathnotice.cpp
  src/game/server/neo/neo_player.cpp
  src/game/shared/neo/neo_gamerules.cpp
  src/game/shared/neo/neo_player_shared.h
  src/game/shared/weapon_parse.cpp
  src/game/shared/weapon_parse.h
Labels: Changes in neoAssets

#1032 original number of smoke layers
  src/game/server/neo/neo_smokegrenade.cpp
Labels: Changes in neoAssets

#1033 Base maps soundscapes
  game/neo/scripts/soundscapes_ntre_bullet_tdm.txt
  game/neo/scripts/soundscapes_ntre_dawn_ctg.txt
  game/neo/scripts/soundscapes_ntre_disengage_ctg.txt
  game/neo/scripts/soundscapes_ntre_dusk_ctg.txt
  game/neo/scripts/soundscapes_ntre_engage_ctg.txt
  game/neo/scripts/soundscapes_ntre_ghost_ctg.txt
  game/neo/scripts/soundscapes_ntre_isolation_ctg.txt
  game/neo/scripts/soundscapes_ntre_redlight_ctg.txt
  game/neo/scripts/soundscapes_ntre_ridgeline_ctg.txt
  game/neo/scripts/soundscapes_ntre_rise_ctg.txt
  game/neo/scripts/soundscapes_ntre_sentinel_ctg.txt
  game/neo/scripts/soundscapes_ntre_shrine_ctg.txt
  game/neo/scripts/soundscapes_ntre_skyline_ctg.txt
  game/neo/scripts/soundscapes_ntre_tarmac_ctg.txt
  game/neo/scripts/soundscapes_ntre_vtol_ctg.txt
Labels: Changes in neoAssets

#1039 Detail.vbsp gitignore
  .gitignore
Labels: Changes in neoAssets

#1050 Func_rotating moving sound fix
  src/game/server/bmodels.cpp
Labels: Mapping
