Repository NeotokyoRebuild/neo, pull requests merged in 2025-09, with the labels that each got.

#1283 Bots - Shoot through glass + penetrateables
  src/game/client/CMakeLists.txt
  src/game/server/CMakeLists.txt
  src/game/server/neo/bot/behavior/neo_bot_attack.cpp
  src/game/server/neo/bot/behavior/neo_bot_behavior.cpp
  src/game/server/neo/bot/behavior/neo_bot_seek_and_destroy.cpp
  src/game/server/neo/bot/behavior/neo_bot_tactical_monitor.cpp
  src/game/server/neo/bot/neo_bot.cpp
  src/game/server/neo/bot/neo_bot.h
  src/game/server/neo/bot/neo_bot_vision.cpp
  src/game/server/neo/bot/neo_bot_vision.h
  src/game/shared/baseentity_shared.cpp
  src/game/shared/decals.h
  src/game/shared/neo/neo_penetration_resistance.cpp
  src/game/shared/neo/neo_penetration_resistance.h
Labels: New Changes for Reviewers

#1334 Sync SDK license legalese with official upstream
  LICENSE
Labels: documentation

#1326 Hide squad list and killfeed if the scoreboard is showing
  src/game/client/neo/ui/neo_hud_deathnotice.cpp
  src/game/client/neo/ui/neo_hud_round_state.cpp
  src/game/client/neo/ui/neo_scoreboard.cpp
Labels: VGUI

#1333 Option to make the round info and scoreboard HUD not swap team sides
  src/game/client/neo/ui/neo_hud_round_state.cpp
  src/game/client/neo/ui/neo_scoreboard.cpp
  src/game/client/neo/ui/neo_scoreboard.h
Labels: VGUI

#1335 Terminal soundscapes
  game/neo/scripts/soundscapes_ntre_terminal_jgr.txt
Labels: Changes in neoAssets

#1159 Dynamic Crosshair
  src/game/client/hud_crosshair.cpp
  src/game/client/hud_crosshair.h
  src/game/client/neo/ui/neo_hud_crosshair.cpp
  src/game/client/neo/ui/neo_hud_crosshair.h
  src/game/client/neo/ui/neo_root_settings.cpp
  src/game/client/neo/ui/neo_root_settings.h
  src/game/shared/neo/neo_player_shared.h
  src/game/shared/neo/weapons/weapon_aa13.h
  src/game/shared/neo/weapons/weapon_bits.h
  src/game/shared/neo/weapons/weapon_jitte.h
  src/game/shared/neo/weapons/weapon_jittes.h
  src/game/shared/neo/weapons/weapon_kyla.h
  src/game/shared/neo/weapons/weapon_m41.h
  src/game/shared/neo/weapons/weapon_m41l.h
  src/game/shared/neo/weapons/weapon_m41s.h
  src/game/shared/neo/weapons/weapon_milso.h
  src/game/shared/neo/weapons/weapon_mpn.h
  src/game/shared/neo/weapons/weapon_mpns.h
  src/game/shared/neo/weapons/weapon_mx.h
  src/game/shared/neo/weapons/weapon_mxs.h
  src/game/shared/neo/weapons/weapon_pbk56s.h
  src/game/shared/neo/weapons/weapon_pz.h
  src/game/shared/neo/weapons/weapon_smac.h
  src/game/shared/neo/weapons/weapon_srm.h
  src/game/shared/neo/weapons/weapon_srms.h
  src/game/shared/neo/weapons/weapon_srs.h
  src/game/shared/neo/weapons/weapon_supa7.h
  src/game/shared/neo/weapons/weapon_tachi.h
  src/game/shared/neo/weapons/weapon_zr68c.h
  src/game/shared/neo/weapons/weapon_zr68l.h
  src/game/shared/neo/weapons/weapon_zr68s.h
Labels: Changes in neoAssets
