Repository NeotokyoRebuild/neo, pull requests merged in 2025-05, with the labels that each got.

#1116 Enable console and fastswitch by default
  src/game/client/neo/ui/neo_root.cpp
  src/game/client/weapon_selection.cpp
Labels: enhancement

#1105 Fix players spawning inside eachother, spawnpoint features, small code cleanup
  src/game/server/neo/neo_game_config.cpp
  src/game/shared/gamerules.cpp
  src/game/shared/neo/neo_player_spawnpoint.cpp
  src/game/shared/neo/neo_player_spawnpoint.h
Labels: Mapping

#1115 Show FetchContent output by default
  src/CMakeLists.txt
Labels: Build System

#1135 Hotfix for black viewmodel bug
  src/game/client/c_baseanimating.cpp
Labels: Bug Report

#1067 Rogue CTG (code)
  .gitignore
  game/neo/scripts/game_sounds_weapons.txt
  game/neo/scripts/soundscapes_ntre_rogue_ctg.txt
  src/game/server/CMakeLists.txt
  src/game/server/neo/neo_npc_targetsystem.cpp
Labels: Changes in neoAssets, Mapping

#1129 Fix broken unicode text in player squad list
  src/game/client/neo/ui/neo_hud_ammo.cpp
  src/game/client/neo/ui/neo_hud_friendly_marker.cpp
  src/game/client/neo/ui/neo_hud_round_state.cpp
Labels: VGUI, Minor bugs

#1141 trigger_serverragdoll applies to players
  src/game/server/neo/neo_player.cpp
  src/game/server/triggers.cpp
Labels: enhancement, Mapping

#1153 Remove obsolete CMake options, speed up dedicated server build on Linux
  src/CMakeLists.txt
  src/game/client/CMakeLists.txt
Labels: Build System, CI
