Repository NeotokyoRebuild/neo, pull requests merged in 2025-08, with the labels that each got.

#1258 Bots - Make them run/sprint properly + CNEOBotContextualQueryInterface
  src/game/server/CMakeLists.txt
  src/game/server/NextBot/NextBotBehavior.h
  src/game/server/NextBot/Player/NextBotPlayer.h
  src/game/server/NextBot/Player/NextBotPlayerLocomotion.cpp
  src/game/server/neo/bot/behavior/neo_bot_behavior.cpp
  src/game/server/neo/bot/behavior/neo_bot_behavior.h
  src/game/server/neo/bot/neo_bot.cpp
  src/game/server/neo/bot/neo_bot.h
  src/game/server/neo/bot/neo_bot_contextual_query_interface.h
  src/game/server/neo/bot/neo_bot_locomotion.cpp
  src/game/server/neo/bot/neo_bot_locomotion.h
  src/game/server/neo/neo_player.cpp
  src/game/server/neo/neo_player.h
Labels: New Changes for Reviewers

#1256 NeoUI - Clipboard + selection + free-cursor for TextEdit
  src/game/client/neo/ui/neo_root.cpp
  src/game/client/neo/ui/neo_root_settings.cpp
  src/game/client/neo/ui/neo_root_settings.h
  src/game/client/neo/ui/neo_scoreboard.cpp
  src/game/client/neo/ui/neo_ui.cpp
  src/game/client/neo/ui/neo_ui.h
  src/game/shared/neo/neo_gamerules.cpp
  src/game/shared/neo/neo_player_shared.cpp
  src/game/shared/neo/neo_player_shared.h
Labels: New Changes for Reviewers

#1271 Ghost Boundary
  src/game/server/CMakeLists.txt
  src/game/server/neo/neo_ghost_boundary.cpp
  src/game/server/neo/neo_ghost_boundary.h
  src/game/shared/neo/neo_gamerules.h
Labels: enhancement, Changes in neoAssets, Mapping

#1190 Killer damage HUD (replacing menu)
  game/neo/scripts/HudLayout.res
  game/neo/scripts/kb_act.lst
  game/neo/scripts/kb_def.lst
  src/game/client/CMakeLists.txt
  src/game/client/c_playerresource.cpp
  src/game/client/neo/c_neo_killer_damage_infos.h
  src/game/client/neo/c_neo_player.cpp
  src/game/client/neo/c_neo_player.h
  src/game/client/neo/ui/neo_hud_deathnotice.cpp
  src/game/client/neo/ui/neo_hud_killer_damage_info.cpp
  src/game/client/neo/ui/neo_hud_killer_damage_info.h
  src/game/client/neo/ui/neo_root_settings.cpp
  src/game/client/neo/ui/neo_root_settings.h
  src/game/server/neo/neo_player.cpp
  src/game/server/neo/neo_player.h
  src/game/shared/neo/neo_gamerules.cpp
  src/game/shared/neo/neo_gamerules.h
  src/game/shared/neo/neo_misc.h
  src/game/shared/neo/neo_player_shared.cpp
  src/game/shared/neo/neo_player_shared.h
Labels: current WIP, New Changes for Reviewers

#1276 Fix client crash
  src/game/client/neo/ui/neo_hud_ammo.cpp
Labels: VGUI
