Repository NeotokyoRebuild/neo, pull requests merged in 2025-07, with the labels that each got.

#1200 Tutorial tweaks hints
  game/neo/resource/neo_english.txt
Labels: Changes in neoAssets

#1082 More contrast in thermals in dark places, hot things in thermals
  src/game/client/c_baseanimating.cpp
  src/game/client/c_baseanimating.h
  src/game/client/c_impact_effects.cpp
  src/game/client/fx_blood.cpp
  src/game/client/fx_explosion.cpp
  src/game/client/fx_sparks.cpp
  src/game/client/fx_sparks.h
  src/game/client/hl2mp/c_hl2mp_player.cpp
  src/game/client/hl2mp/c_hl2mp_player.h
  src/game/client/particle_iterators.h
  src/game/client/particlemgr.cpp
  src/game/client/particlemgr.h
  src/game/client/particles_simple.cpp
  src/game/client/particles_simple.h
  src/game/client/proxyplayer.cpp
  src/game/client/ragdoll.cpp
  src/game/server/baseanimating.cpp
  src/game/server/baseanimating.h
  src/game/server/gib.cpp
  src/game/server/neo/neo_model_manager.cpp
  src/game/server/neo/neo_player.cpp
  src/game/shared/basecombatweapon_shared.cpp
  src/game/shared/neo/neo_player_shared.h
  src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
  src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
  src/game/shared/sdk/sdk_basegrenade_projectile.cpp
  src/game/shared/sdk/sdk_basegrenade_projectile.h
  src/materialsystem/stdshaders/Neo_ThermalVision.cpp
  src/materialsystem/stdshaders/buildneoshaders.bat
  src/materialsystem/stdshaders/include/neo_Refract_vs20.inc
  src/materialsystem/stdshaders/include/neo_motion_model_ps20b.inc
  src/materialsystem/stdshaders/include/neo_motion_model_vs20.inc
  src/materialsystem/stdshaders/include/neo_motionvision_pass2_ps30.inc
  src/materialsystem/stdshaders/include/neo_nightvision_ps30.inc
  src/materialsystem/stdshaders/include/neo_refract_ps20b.inc
  src/materialsystem/stdshaders/include/neo_testshader_ps20b.inc
  src/materialsystem/stdshaders/include/neo_thermal_model_ps20b.inc
  src/materialsystem/stdshaders/include/neo_thermal_model_vs20.inc
  src/materialsystem/stdshaders/include/neo_thermalvision_ps30.inc
  src/materialsystem/stdshaders/neo_thermal_model_dx9.cpp
  src/materialsystem/stdshaders/neo_thermal_model_dx9_helper.h
  src/materialsystem/stdshaders/neo_thermal_model_ps20b.fxc
  src/materialsystem/stdshaders/neo_thermalvision_ps30.fxc
  src/materialsystem/stdshaders/neoshader_dx9_20b.txt
  src/materialsystem/stdshaders/neoshader_dx9_30.txt
Labels: enhancement, Changes in neoAssets

#1218 Spray handling improvements - Freezetime, disabled spray, cleanups
  src/game/client/c_te_playerdecal.cpp
  src/game/client/cdll_client_int.cpp
  src/game/server/player.cpp
Labels: New Changes for Reviewers

#1217 Balli & Marketa Soundscapes
  game/neo/scripts/soundscapes_ntre_ballistrade_ctg.txt
  game/neo/scripts/soundscapes_ntre_marketa_ctg.txt
Labels: Changes in neoAssets

#1232 Revert NeoUI mouse handling change, -tools loads up legacy main menu instead
  src/game/client/cdll_client_int.cpp
  src/game/client/clientmode_shared.cpp
  src/game/client/neo/ui/neo_root.cpp
  src/game/client/neo/ui/neo_root.h
  src/game/client/vgui_int.cpp
Labels: New Changes for Reviewers

#1231 Keybind support for neo_message, and extra line for keybinds
  game/neo/resource/neo_english.txt
  src/game/client/neo/c_neo_message.cpp
  src/game/client/neo/c_neo_message.h
  src/game/client/neo/ui/neo_hud_message.cpp
  src/game/client/neo/ui/neo_hud_message.h
  src/game/server/neo/neo_message.cpp
  src/game/server/neo/neo_message.h
Labels: VGUI, Changes in neoAssets, Mapping, Tutorial
