Repository NeotokyoRebuild/neo, pull requests merged in 2025-02, with the labels that each got.

#866 Pre-round hints on HUD
  mp/game/neo/scripts/HudLayout.res
  mp/src/game/client/CMakeLists.txt
  mp/src/game/client/neo/ui/neo_hud_hint.cpp
  mp/src/game/client/neo/ui/neo_hud_hint.h
Labels: VGUI

#847 KillFeed weapon icons
  mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
  mp/src/game/client/hl2mp/hud_deathnotice.cpp
Labels: Changes in neoAssets

#799 Cloak fixes
  mp/src/game/client/neo/c_neo_player.cpp
  mp/src/game/server/neo/neo_player.cpp
  mp/src/game/server/neo/neo_player.h
  mp/src/game/shared/neo/neo_player_shared.h
Labels: New Changes for Reviewers

#888 background maps and menu tweaks
  mp/game/neo/resource/ClientScheme.res
  mp/game/neo/resource/neotokyo_press_n.ttf
  mp/game/neo/scripts/ChapterBackgrounds.txt
  mp/src/game/client/neo/ui/neo_loading.cpp
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/client/neo/ui/neo_root_settings.cpp
  mp/src/game/client/neo/ui/neo_root_settings.h
  mp/src/game/client/neo/ui/neo_ui.cpp
  mp/src/game/client/neo/ui/neo_ui.h
  mp/src/game/client/view.cpp
  mp/src/game/shared/baseplayer_shared.cpp
Labels: Changes in neoAssets

#896 Fix incorrect version info string display in main menu
  mp/src/game/client/neo/ui/neo_root.cpp
  mp/src/game/shared/neo/neo_version_info.cpp.in
  mp/src/game/shared/neo/neo_version_info.h
Labels: VGUI, Minor bugs
